import { defineConfig } from "vite-plus";

export default defineConfig({
  pack: {
    entry: {
      index: "src/index.ts",
      "locales/en": "src/locales/en.ts",
      "locales/de": "src/locales/de.ts",
      "locales/es": "src/locales/es.ts",
      "locales/fr": "src/locales/fr.ts",
      "locales/nl": "src/locales/nl.ts",
      "locales/tr": "src/locales/tr.ts",
      "locales/cs": "src/locales/cs.ts",
      "locales/pl": "src/locales/pl.ts",
    },
    unbundle: true,
    dts: {
      tsgo: true,
    },
    exports: true,
    publint: {
      level: "error",
    },
    attw: {
      profile: "esm-only",
      level: "error",
    },
  },
  lint: {
    ignorePatterns: [
      ".agent/**",
      ".agents/**",
      ".claude/**",
      ".codex/**",
      ".continue/**",
      ".cursor/**",
      ".gemini/**",
      ".opencode/**",
      ".pi/**",
      ".roo/**",
      ".windsurf/**",
      "tools/oxlint/anti-slop/**",
    ],
    jsPlugins: [
      {
        name: "anti-slop",
        specifier: "./tools/oxlint/anti-slop/index.ts",
      },
      {
        name: "anti-slop-effect",
        specifier: "./tools/oxlint/anti-slop/effect/index.ts",
      },
    ],
    options: {
      typeAware: true,
      typeCheck: true,
    },
    rules: {
      "anti-slop/no-chained-type-assertions": "error",
      "anti-slop/no-conditional-empty-object-spread": "error",
      "anti-slop/no-explicit-return-types": "error",
      "anti-slop/no-internal-export-all": "error",
      "anti-slop/no-known-value-widening": "error",
      "anti-slop/no-manual-tags": "error",
      "anti-slop/no-module-mocking": "error",
      "anti-slop/no-nested-ternaries": "error",
      "anti-slop/no-object-parameters": "error",
      "anti-slop/no-reflect-apply": "error",
      "anti-slop/no-reflect-get": "error",
      "anti-slop/no-runtime-typeof": "error",
      "anti-slop/no-shape-in-symbol-names": "error",
      "anti-slop/no-switch-statements": "error",
      "anti-slop/no-unknown-parameters": "error",
      "anti-slop/no-unknown-returns": "error",
      "anti-slop/no-unknown-type-aliases": "error",
      "anti-slop/no-unsafe-dictionary-type": "error",
      "anti-slop/no-widen-then-assert": "error",
      "anti-slop/require-safety-comment-for-type-assertion": "error",
      "anti-slop-effect/no-service-constructor-imports": "error",
      "anti-slop-effect/prefer-effect-fn": "error",
    },
  },
  fmt: {
    ignorePatterns: [
      ".agent/**",
      ".agents/**",
      ".claude/**",
      ".codex/**",
      ".continue/**",
      ".cursor/**",
      ".gemini/**",
      ".opencode/**",
      ".pi/**",
      ".roo/**",
      ".windsurf/**",
      "tools/oxlint/anti-slop/**",
    ],
  },
  test: {
    include: ["tests/**/*.test.ts"],
  },
});
